### ISSUE TITLE
how to chainload multiple dll?

### ISSUE THREAD

**Issue by iznawh** [Aluerie/Sekiro-ShiftCombatArt#3]
Hi,
I want to use this with [https://github.com/ReaperAnon/SekiroHotkeySystem](url) , but both of ur mods require the 
"dinput8.dll" and i dont know how to chainload multiple or is that even possible? 

Thank you

**Comment by Aluerie** [comment]
Hey, I'm sorry, I don't know how your message slipped through my notifications unnoticed...

First, I'm not sure why would you use these mods together, my mod won't magically adjust to Combat Art chosen in SekiroHotkeySystem. My mod is pretty dumped-down and hardcoded since I'm not proficient with C++.

---

But okay, I updated README.md to make instructions a bit more clear.

--- 

The easiest path in your case is probably... 

I guess you are using Mod Engine already because 99% of mod users do so. And if not you probably will want to install it anyway because 99% of mods utilize it... 

Let's organize chain-loading: `ModEngine` ➡️ `HotkeySystem` ➡️ `ShiftArt`.

So the steps are as follows:
1. Download just updated Release of my mod from [Releases Tab](https://github.com/Aluerie/Sekiro-ShiftCombatArt/releases), unwrap it and paste it into the same folder with `sekiro.exe`.
2. Organize `ModEngine` ➡️ `HotkeySystem` part of the chain
    * Rename SekiroHotkeySystem's `.dll` file to something like `hotkey_system.dll`
    * In `modengine.ini` point to mentioned `.dll`-file by changing the line `chainDInput8DLLPath=""` to `chainDInput8DLLPath="\hotkey_system.dll"` 
    * The "`\`" is important
3. Now to `HotkeySystem` ➡️ `ShiftArt` part of the chain
    *  go to `configs/chainload.ini`
    *  change the line `chainDllName = ""` to `chainDllName = "\shift_art.dll"`

Now all mods should chain load each other just fine.

**Comment by iznawh** [comment]
well thats because even with the hotkey system sometimes when i press block then attack too fast i end up doing a combat art and your mod seems to fix that problem :] edit: ty for the fast fix!
